workflows:
  ios-testflight:
    name: iOS TestFlight

    integrations:
      app_store_connect: trishaki

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hitechpragati.app

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up iOS signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.3 \
            --build-number=10 \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true